# This is a basic workflow to help you get started with Actions
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps: 
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.jacobs36.sg-host.com
        username: deploy
        password: ${{ secrets.ftp_password }}
